<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Заказ ключа PROKMLM Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'index.html#top',
	'resources' => array(
		'checkbox_checked' => 'Selected',
		'checkbox_unchecked' => 'Unselected',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '8877024@gmail.com',
		'to' => '8877024@gmail.com'
	),
	'fields' => array(
		'custom_U5824' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Как к вам обращаться?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Как к вам обращаться?\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Ваш Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ваш Email\' is required.',
				'format' => 'Field \'Ваш Email\' has an invalid email address.'
			)
		),
		'custom_U5869' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Ваш телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ваш телефон\' is required.'
			)
		),
		'custom_U5921' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Ваш скайп',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ваш скайп\' is required.'
			)
		),
		'custom_U6038' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Ссылка на страницу в социальных сетях',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ссылка на страницу в социальных сетях\' is required.'
			)
		),
		'custom_U5945' => array(
			'order' => 6,
			'type' => 'radiogroup',
			'label' => 'Каким способом вам удобно оплатить ключ?',
			'required' => true,
			'optionItems' => array(
				'На карту сбербанка',
				'На яндекс деньги',
				'На Qiwi кошелёк',
				'Другое'
			),
			'errors' => array(
				'required' => 'Field \'Каким способом вам удобно оплатить ключ?\' is required.',
				'format' => 'Field \'Каким способом вам удобно оплатить ключ?\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
